/* ══════════════════ DATA ══════════════════ */
const projects = [
  {
    id: 1,
    title: "Robo Race Bot",
    shortDesc: "High-speed 4WD racing robot with wireless control",
    detailedExplanation: "This is a high-speed robotic vehicle designed for competitive racing, featuring a powerful 4-wheel drive system for strong torque and fast acceleration. It is powered by a LiPo battery to ensure consistent high performance during races. The bot uses motor drivers for smooth and precise control of all motors. A wireless transmitter-receiver setup allows real-time control with responsive steering and throttle. The lightweight yet durable chassis ensures stability and speed on racing tracks.",
    componentsUsed: "DC geared motors (4x), Wheels (4x), Motor drivers (BTS7960 – 2x), RC transmitter & receiver, LiPo battery (3S 11.1V), Chassis/frame, Buck converter, Power switch, Connecting wires, Connectors (XT60), Arduino Uno",
    workingExplanation: "The robo race bot works on a wireless control system using a transmitter and receiver. When the user gives input through the transmitter (throttle or steering), signals are sent to the receiver mounted on the bot. These signals are then forwarded to the motor drivers, which control the speed and direction of the DC motors. The LiPo battery supplies high current to drive all four motors efficiently. By varying the PWM signals, the bot achieves smooth acceleration, braking, and turning, allowing precise control during races.",
    embedUrl: "https://www.youtube.com/embed/bl2gWOpC4_4"
  },
  {
    id: 2,
    title: "Eye Controlled Car",
    shortDesc: "Hands-free robotic car using AI eye tracking",
    detailedExplanation: "This project is a hands-free robotic car controlled using eye movements through real-time computer vision. It uses OpenCV and MediaPipe to detect eye direction and convert it into control commands. An ESP32 receives these commands wirelessly and controls the motors accordingly. The system is designed for low latency, ensuring quick response to eye movements. It demonstrates the integration of AI and embedded systems for assistive technology.",
    componentsUsed: "DC motors, ESP32, Motor driver L298N, Wheels, Chassis, Battery (LiPo or 18650 pack), USB camera / laptop camera, Jumper wires, Power module, OpenCV, MediaPipe",
    workingExplanation: "The system starts with a camera capturing the user's face in real time. Using OpenCV and MediaPipe, the eye position and gaze direction are detected. Based on this, commands like left, right, or forward are generated by the program. These commands are sent wirelessly to the ESP32, which controls the motor driver and moves the car accordingly. The entire system works in real time, enabling hands-free navigation.",
    embedUrl: "https://www.youtube.com/embed/LPo3su2wmzA"
  },
  {
    id: 3,
    title: "RFID Attendance System",
    shortDesc: "Automated attendance using RFID technology",
    detailedExplanation: "This is an automated attendance system that uses RFID technology to identify users through unique cards. When a card is scanned, the system verifies its ID using Arduino Uno. If the card is valid, attendance is marked and a green LED glows as confirmation. The system is fast, reliable, and reduces manual errors. Ideal for schools, offices, and basic automation projects.",
    componentsUsed: "RFID module (MFRC522), Arduino Uno, Green LED, Resistor (220Ω), Breadboard, Jumper wires, USB cable",
    workingExplanation: "When an RFID card is brought near the reader, the RFID module scans the card's unique ID using radio frequency signals. This data is sent to the Arduino Uno, which checks whether the ID matches stored authorized IDs. If valid, the system marks attendance and turns on a green LED as confirmation. If unrecognized, no action is triggered. This process happens instantly, making attendance marking fast and accurate.",
    embedUrl: "https://www.youtube.com/embed/uIu3_PnATQU"
  },
  {
    id: 4,
    title: "NEXUS Delivery Bot",
    shortDesc: "Smart ESP32-based autonomous delivery robot with obstacle detection, anti-theft protection, and web-controlled navigation",
    detailedExplanation: "This is an ESP32-based smart delivery robot designed for indoor autonomous transportation and safety applications. It uses a web-based control system that allows users to send movement commands wirelessly through a custom interface. The robot features LiDAR obstacle detection for collision prevention and an ultrasonic sensor-based anti-theft system that activates a buzzer if the robot is lifted. Its powerful geared motors and large rubber wheels provide stable movement and smooth navigation.",
    componentsUsed: "ESP32 Development Board, BTS7960 Motor Driver, 300 RPM DC Geared Motors, 125 mm Rubber Wheels, LiPo Battery, XT60 Connector, Buck Converter, VL53L0X LiDAR Sensor, Ultrasonic Sensor, Buzzer Module, Chassis/Frame, Connecting Wires",
    workingExplanation: "The Nexus delivery bot works using an ESP32 microcontroller that creates its own WiFi network and hosts a control webpage. Users can queue commands like forward, backward, left, and right with adjustable distances. The BTS7960 motor driver controls the motors for smooth movement, while the LiDAR sensor continuously checks for obstacles and stops the robot automatically when needed. An ultrasonic sensor underneath the robot acts as an anti-theft system by activating the buzzer whenever the robot is lifted from the ground.",
    embedUrl: "https://www.youtube.com/embed/Oy_LwHAHLSg"
  }
];

/* ══════════════════ HELPERS ══════════════════ */
const $ = id => document.getElementById(id);
const getVideoId = u => (u.match(/\/embed\/([^?]+)/) || [])[1] || null;
const getThumb = u => {
  const id = getVideoId(u);
  return id ? `https://img.youtube.com/vi/${id}/mqdefault.jpg` : 'https://via.placeholder.com/320x180/040912/00f5ff?text=SteelCircuits';
};
const esc = s => (s||'').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

/* ══════════════════ CURSOR FOLLOWER ══════════════════ */
(function setupCursor() {
  if (matchMedia('(pointer: coarse)').matches) return;
  const orb = $('cursorOrb'), dot = $('cursorDot');
  let mx = innerWidth/2, my = innerHeight/2, ox = mx, oy = my;

  addEventListener('mousemove', e => {
    mx = e.clientX; my = e.clientY;
    dot.style.transform = `translate(${mx}px, ${my}px) translate(-50%, -50%)`;
  });

  const HOVER_SEL = 'a, button, .video-card, .tech-logo-item, .skill, .stat-item, input, textarea';
  document.addEventListener('mouseover', e => { if (e.target.closest(HOVER_SEL)) document.body.classList.add('cursor-hover'); });
  document.addEventListener('mouseout',  e => { if (e.target.closest(HOVER_SEL)) document.body.classList.remove('cursor-hover'); });

  (function loop() {
    ox += (mx - ox) * 0.18;
    oy += (my - oy) * 0.18;
    orb.style.transform = `translate(${ox}px, ${oy}px) translate(-50%, -50%)`;
    requestAnimationFrame(loop);
  })();
})();

/* ══════════════════ SCROLL REVEAL ══════════════════ */
const scrollObserver = new IntersectionObserver(entries => {
  entries.forEach(e => { if (e.isIntersecting) e.target.classList.add('revealed'); });
}, { threshold: 0.1, rootMargin: '0px 0px -30px 0px' });

function observeReveals() {
  document.querySelectorAll('.scroll-reveal:not(.revealed)').forEach(el => scrollObserver.observe(el));
}

/* ══════════════════ HEADER SCROLL STATE ══════════════════ */
(function setupHeaderScroll() {
  const header = $('siteHeader');
  window.addEventListener('scroll', () => {
    header.classList.toggle('scrolled', window.scrollY > 40);
  }, { passive: true });
})();

/* ══════════════════ ACTIVE NAV ON SCROLL ══════════════════ */
function setupActiveNav() {
  const sections = document.querySelectorAll('[id]');
  const navLinks = document.querySelectorAll('.nav-link');

  const obs = new IntersectionObserver(entries => {
    entries.forEach(entry => {
      if (entry.isIntersecting) {
        navLinks.forEach(link => {
          link.classList.toggle('active', link.getAttribute('href') === `#${entry.target.id}`);
        });
      }
    });
  }, { threshold: 0.35 });

  sections.forEach(s => { if (s.id) obs.observe(s); });
}

/* ══════════════════ MOBILE HAMBURGER ══════════════════ */
function setupMobileNav() {
  const btn = $('hamburger'), nav = $('navLinks');
  btn?.addEventListener('click', () => {
    nav.classList.toggle('open');
    btn.classList.toggle('open');
  });
  document.querySelectorAll('.nav-link').forEach(link => {
    link.addEventListener('click', () => {
      nav.classList.remove('open');
      btn.classList.remove('open');
    });
  });
}

/* ══════════════════ WA BANNER ══════════════════ */
function showWaBanner() {
  const b = $('waBanner');
  b.classList.add('show');
  setTimeout(() => b.classList.remove('show'), 4200);
}

/* ══════════════════ HOME GRID ══════════════════ */
function renderHomeGrid(filter = '') {
  const grid = $('videoGridContainer'), noRes = $('noResults'), badge = $('projectCount');
  const q = filter.trim().toLowerCase();
  const list = q
    ? projects.filter(p =>
        p.title.toLowerCase().includes(q) ||
        p.shortDesc.toLowerCase().includes(q) ||
        p.componentsUsed.toLowerCase().includes(q))
    : projects;

  badge.textContent = `${list.length} project${list.length !== 1 ? 's' : ''}`;
  if (!list.length) {
    grid.innerHTML = '';
    $('noResultsQuery').textContent = filter;
    noRes.style.display = 'block';
    return;
  }
  noRes.style.display = 'none';
  grid.innerHTML = list.map((p, i) => `
    <div class="video-card scroll-reveal" data-delay="${Math.min(5, i+1)}" data-id="${p.id}">
      <div class="thumbnail">
        <img src="${getThumb(p.embedUrl)}" alt="${esc(p.title)}" loading="lazy"
             onerror="this.src='https://via.placeholder.com/320x180/040912/00f5ff?text=SteelCircuits'">
        <div class="play-overlay"><i class="fas fa-play-circle"></i></div>
      </div>
      <div class="card-content">
        <div class="card-title">${esc(p.title)}</div>
        <div class="card-desc">${esc(p.shortDesc)}</div>
      </div>
    </div>`).join('');

  grid.querySelectorAll('.video-card').forEach(c =>
    c.addEventListener('click', () => openModal(parseInt(c.dataset.id)))
  );
  observeReveals();
}

/* ══════════════════ PROJECT MODAL ══════════════════ */
function openModal(id) {
  const p = projects.find(x => x.id === id);
  if (!p) return;
  const embed = p.embedUrl.split('?')[0];
  const badges = p.componentsUsed.split(',').map(c => c.trim()).filter(Boolean)
    .map(c => `<span class="badge">⚡ ${esc(c)}</span>`).join('');

  $('projectDetailContent').innerHTML = `
    <div class="video-player-container">
      <div class="video-wrapper">
        <iframe src="${embed}?rel=0&modestbranding=1"
          allow="accelerometer;autoplay;clipboard-write;encrypted-media;gyroscope;picture-in-picture"
          allowfullscreen></iframe>
      </div>
    </div>
    <div class="project-detail-info">
      <h2 class="detail-title">${esc(p.title)}</h2>
      <div class="detail-section">
        <h3><i class="fas fa-info-circle"></i> Detailed Explanation</h3>
        <p>${esc(p.detailedExplanation)}</p>
      </div>
      <div class="detail-section">
        <h3><i class="fas fa-microchip"></i> Components Used</h3>
        <div class="components-badge">${badges}</div>
      </div>
      <div class="detail-section">
        <h3><i class="fas fa-cogs"></i> Working Explanation</h3>
        <p>${esc(p.workingExplanation)}</p>
      </div>
    </div>`;

  const modal = $('projectModal');
  modal.classList.add('open');
  document.body.style.overflow = 'hidden';
}

function closeModal() {
  $('projectModal').classList.remove('open');
  document.body.style.overflow = '';
  $('projectDetailContent').innerHTML = '';
}

function setupModal() {
  $('modalCloseBtn')?.addEventListener('click', closeModal);
  $('projectModal')?.addEventListener('click', e => {
    if (e.target === $('projectModal')) closeModal();
  });
  document.addEventListener('keydown', e => {
    if (e.key === 'Escape') closeModal();
  });
}

/* ══════════════════ SEARCH ══════════════════ */
function setupSearch() {
  const input = $('searchInput');
  if (!input) return;
  let t;
  input.addEventListener('input', () => {
    clearTimeout(t);
    t = setTimeout(() => renderHomeGrid(input.value), 220);
  });
}

/* ══════════════════ CONTACT ══════════════════ */
function setupContact() {
  $('contactForm')?.addEventListener('submit', e => {
    e.preventDefault();
    const name = $('contactName').value.trim();
    const msg  = $('contactMsg').value.trim();
    if (!name || !msg) return;
    const text = `*SteelCircuits Contact*%0A%0A*Name:* ${encodeURIComponent(name)}%0A*Message:* ${encodeURIComponent(msg)}%0A%0A(From Robotics Showcase)`;
    window.open(`https://wa.me/917303177088?text=${text}`, '_blank');
    showWaBanner();
    e.target.reset();
  });
}

/* ══════════════════ STAT COUNTERS ══════════════════ */
function setupStatCounters() {
  const els = document.querySelectorAll('.stat-number[data-target]');
  const obs = new IntersectionObserver(entries => {
    entries.forEach(entry => {
      if (!entry.isIntersecting) return;
      obs.unobserve(entry.target);
      const el = entry.target;
      const target = parseInt(el.dataset.target, 10);
      const suffix = el.dataset.suffix || '';
      const duration = 1400;
      const start = performance.now();

      function tick(now) {
        const t = Math.min((now - start) / duration, 1);
        const eased = 1 - Math.pow(1 - t, 3);
        el.textContent = Math.floor(eased * target) + suffix;
        if (t < 1) requestAnimationFrame(tick);
      }
      requestAnimationFrame(tick);
    });
  }, { threshold: 0.6 });

  els.forEach(el => obs.observe(el));
}

/* ══════════════════ SMOOTH ANCHOR SCROLL ══════════════════ */
function setupSmoothScroll() {
  document.querySelectorAll('a[href^="#"]').forEach(link => {
    link.addEventListener('click', e => {
      const target = document.querySelector(link.getAttribute('href'));
      if (!target) return;
      e.preventDefault();
      const offset = 80;
      const top = target.getBoundingClientRect().top + window.scrollY - offset;
      window.scrollTo({ top, behavior: 'smooth' });
    });
  });
}

/* ══════════════════ INIT ══════════════════ */
function init() {
  renderHomeGrid();
  setupSearch();
  setupContact();
  setupModal();
  setupMobileNav();
  setupActiveNav();
  setupStatCounters();
  setupSmoothScroll();
  observeReveals();
}
init();
